/*-
 * Written by Dridi Boukelmoune <dridi.boukelmoune@gmail.com>
 *
 * This file is in the public domain.
 *
 * HPACK: Static Table Definition (RFC 7540 Appendix A)
 */

HPS(":authority",                  "")
HPS(":method",                     "GET")
HPS(":method",                     "POST")
HPS(":path",                       "/")
HPS(":path",                       "/index.html")
HPS(":scheme",                     "http")
HPS(":scheme",                     "https")
HPS(":status",                     "200")
HPS(":status",                     "204")
HPS(":status",                     "206")
HPS(":status",                     "304")
HPS(":status",                     "400")
HPS(":status",                     "404")
HPS(":status",                     "500")
HPS("accept-charset",              "")
HPS("accept-encoding",             "gzip, deflate")
HPS("accept-language",             "")
HPS("accept-ranges",               "")
HPS("accept",                      "")
HPS("access-control-allow-origin", "")
HPS("age",                         "")
HPS("allow",                       "")
HPS("authorization",               "")
HPS("cache-control",               "")
HPS("content-disposition",         "")
HPS("content-encoding",            "")
HPS("content-language",            "")
HPS("content-length",              "")
HPS("content-location",            "")
HPS("content-range",               "")
HPS("content-type",                "")
HPS("cookie",                      "")
HPS("date",                        "")
HPS("etag",                        "")
HPS("expect",                      "")
HPS("expires",                     "")
HPS("from",                        "")
HPS("host",                        "")
HPS("if-match",                    "")
HPS("if-modified-since",           "")
HPS("if-none-match",               "")
HPS("if-range",                    "")
HPS("if-unmodified-since",         "")
HPS("last-modified",               "")
HPS("link",                        "")
HPS("location",                    "")
HPS("max-forwards",                "")
HPS("proxy-authenticate",          "")
HPS("proxy-authorization",         "")
HPS("range",                       "")
HPS("referer",                     "")
HPS("refresh",                     "")
HPS("retry-after",                 "")
HPS("server",                      "")
HPS("set-cookie",                  "")
HPS("strict-transport-security",   "")
HPS("transfer-encoding",           "")
HPS("user-agent",                  "")
HPS("vary",                        "")
HPS("via",                         "")
HPS("www-authenticate",            "")
