#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019-2021 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

if { $argc != 2 } {
	puts "TESTING ERROR: argument missing"
	puts "Usage: test-keepalive.exp server-name proxy-addr"
	exit
}

set configured [exec fdns --list=[lindex $argv  0]]

send -- "fdns --proxy-addr=[lindex $argv  1] --server=[lindex $argv  0] --debug-transport --resolvers=1 --keepalive=600>&1\r"
expect {
	timeout {puts "TESTING ERROR 0 - $argv\n";exit 1}
	"fdns starting"
}
expect {
	timeout {puts "TESTING ERROR 2 - $argv\n";exit 1}
	"SSL connection opened"
}
set start [exec "date" "+%s"]
sleep 1

set timeout 620
puts "waiting 620 seconds for keepalive test to finish"

expect {
	timeout {puts "\nTESTING: [lindex $argv  0] - 600+\n";exit 0}
	"SSL connection closed" {puts "$configured\n"; set end [exec "date" "+%s"]; set delta [expr "$end - $start"]; puts "TESTING: [lindex $argv  0] - $delta\n";
		puts "TESTING**************************************************\n";exit 1}
	"it will never get here"
}

after 100
puts "TESTING ERROR 4 - $argv\n"
exit 1
