#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019-2020 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

spawn $env(SHELL)
send -- "firejail --dns=127.1.1.1 ../src/fdnstress/fdnstress --threads=10 ./list500\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Aws.amazon.com"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Computerworld.com.au"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Easeus.com"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Gnome.org"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"Klipfolio.com"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"Netgear.com"
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"Pixlr.com"
}
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"Smallpdf.com"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"Tmall.com"
}
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"Zyxel.com"
}

sleep 12
set ping_id $spawn_id

spawn $env(SHELL)
set monitor_id $spawn_id
send -- "fdns --monitor\r"
expect {
	timeout {puts "TESTING ERROR 11\n";exit}
	"requests 1000, dropped 500"
}
after 100
puts "\nall done\n"

