#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019-2020 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

if { $argc != 2 } {
	puts "TESTING ERROR: argument missing"
	puts "Usage: test-keepalive.exp server-name proxy-addr"
	exit
}

puts "TESTING keepalive: [lindex $argv  0] [lindex $argv  1]"

send -- "fdns --proxy-addr=[lindex $argv  1] --server=[lindex $argv  0] --debug-transport --resolvers=1>&1\r"
expect {
	timeout {puts "TESTING ERROR 0 - $argv\n";exit 1}
	"fdns starting"
}
expect {
	timeout {puts "TESTING ERROR 2 - $argv\n";exit 1}
	"SSL connection opened"
}
sleep 1

set timeout 320
puts "waiting 95 seconds for keepalive test to finish"

expect {
	timeout {puts "\nTESTING: all done [lindex $argv  0]\n";exit 0}
	"SSL connection closed" {puts "TESTING ERROR 3 - $argv\n";exit 1}
	"it will never get here"
}

after 100
puts "TESTING ERROR 4 - $argv\n"
exit 1
