#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019-2020 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

if { $argc != 2 } {
	puts "TESTING ERROR: argument missing"
	puts "Usage: test-server.exp server-name proxy-addr"
	exit
}

puts "TESTING query: [lindex $argv  1] [lindex $argv  0]"

send -- "fdns --server=[lindex $argv  0] --proxy-addr=[lindex $argv  1]  2>&1\r"
expect {
	timeout {puts "TESTING ERROR 0 $argv \n";exit 1}
	"Error:" {puts "TESTING ERROR 1 $argv \n";exit 1}
	"fdns starting"
}
expect {
	timeout {puts "TESTING ERROR 2 $argv \n";exit 1}
	"SSL connection opened"
}
expect {
	timeout {puts "TESTING ERROR 3 $argv \n";exit 1}
	"SSL connection opened"
}
expect {
	timeout {puts "TESTING ERROR 4 $argv \n";exit 1}
	"SSL connection opened"
}
sleep 1

spawn $env(SHELL)
send -- "cp ../src/fdnstress/fdnstress /transfer/.\r"
send -- "cp list20  /transfer/.\r"
after 100
send -- "firejail --dns=[lindex $argv  1]  /transfer/fdnstress --threads=1 /transfer/list20\r"
expect {
	timeout {puts "TESTING ERROR 30 $argv \n";exit 1}
	"Error:" {puts "TESTING ERROR 30.1 $argv \n";exit 1}
	"SSL connection closed" {puts "TESTING ERROR 30.2 $argv \n";exit 1}
	"wordpress.com"
}
expect {
	timeout {puts "TESTING ERROR 31 $argv \n";exit 1}
	"Error:" {puts "TESTING ERROR 31.1 $argv \n";exit 1}
	"SSL connection closed" {puts "TESTING ERROR 31.2 $argv \n";exit 1}
	"linux.org"
}
expect {
	timeout {puts "TESTING ERROR 32 $argv \n";exit 1}
	"Error:" {puts "TESTING ERROR 32.1 $argv \n";exit 1}
	"SSL connection closed" {puts "TESTING ERROR 32.2 $argv \n";exit 1}
	"google.com"
}
expect {
	timeout {puts "TESTING ERROR 33 $argv \n";exit 1}
	"Error:" {puts "TESTING ERROR 33.1 $argv \n";exit 1}
	"SSL connection closed" {puts "TESTING ERROR 33.2 $argv \n";exit 1}
	"youtube.com"
}
expect {
	timeout {puts "TESTING ERROR 34 $argv \n";exit}
	"Error:" {puts "TESTING ERROR 34.1 $argv \n";exit 1}
	"SSL connection closed" {puts "TESTING ERROR 34.2 $argv \n";exit 1}
	"fedoraproject.org"
}

after 100
puts "\nall done\n"
