#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019-2020 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

if { $argc != 1 } {
	puts "TESTING ERROR: argument missing"
	puts "Usage: wget.exp server-name"
	exit
}

puts "TESTING: $argv"

send -- "pkill fdns\r"
sleep 1

send -- "fdns --server=$argv 2>&1\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit 1}
	"Error:" {puts "TESTING ERROR 0.1\n";exit 1}
	"fdns starting"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit 1}
	"SSL connection opened"
}

# wait 10 seconds to detect any kind of connection problems
#expect {
#	timeout {puts "connection OK\n"}
#	"Error:" {puts "TESTING ERROR 2\n";exit 1}
#	"SSL connection closed" {puts "TESTING ERROR 3\n";exit 1}
#}
sleep 1

spawn $env(SHELL)
send "rm /tmp/index.html\r"
after 100
send -- "firejail --dns=127.1.1.1 wget -O /tmp/index.html google.com\r"
expect {
	timeout {puts "TESTING ERROR 10\n";exit 1}
	"Connecting to www.google.com"
}
expect {
	timeout {puts "TESTING ERROR 11\n";exit 1}
	"index.html"
}
expect {
	timeout {puts "TESTING ERROR 12\n";exit 1}
	"saved"
}
sleep 1

# do it again!
send "rm /tmp/index.html\r"
after 100
send -- "firejail --dns=127.1.1.1 wget -O /tmp/index.html wordpress.com\r"
expect {
	timeout {puts "TESTING ERROR 13\n";exit 1}
	"Connecting to wordpress.com"
}
expect {
	timeout {puts "TESTING ERROR 14\n";exit 1}
	"index.html"
}
expect {
	timeout {puts "TESTING ERROR 15\n";exit 1}
	"saved"
}
after 100
send "rm /tmp/index.html\r"
send -- "pkill fdns\r"

after 100
puts "\nall done\n"
