#include "fdns.h"

static char *sni_list[] = {
	"adayinthelifeonthefarm.blogspot.com",
	"allshecooks.com",
	"amindfullmom.com",
	"anitalianinmykitchen.com",
	"aspoonfulofthyme.blogspot.com",
	"bad-girls-kitchen.blogspot.com",
	"bakingbites.com",
	"bitterbaker.com",
	"bizzybakesb.blogspot.com",
	"bunnyswarmoven.net",
	"cheesecurdinparadise.blogspot.com",
	"dishaboutit.com",
	"easilygoodeats.blogspot.com",
	"funnyloveblog.com",
	"gingerbakes.wordpress.com",
	"jennsrandomscraps.blogspot.ca",
	"joandsue.blogspot.ca",
	"joinuspullupachair.blogspot.com",
	"livingthegourmet.com",
	"lovelylittlekitchen.com",
	"marthasvillage.org",
	"mimis-kitchen.blogspot.com",
	"morethanburnttoast.blogspot.ca",
	"nutritionfor.us",
	"ohmysugarhigh.com",
	"redstaryeast.com",
	"seasonalandholidayrecipeexchange.weebly.com",
	"spaceshipsandlaserbeams.com",
	"sweetsbeginning.blogspot.com",
	"swirlsandspice.com",
	"tascadaelvira.blogspot.com",
	"thecharmofhome.blogspot.com",
	"thefreshmancook.blogspot.com",
	"thepioneerwoman.com",
	"therebelchick.com",
	"thissillygirlslife.com",
	"vegukate.com",
	"whoneedsacape.com",
	"www.allrecipes.com",
	"www.averiecooks.com",
	"www.bakeorbreak.com",
	"www.browneyedbaker.com",
	"www.cookingchanneltv.com",
	"www.cookingonthefrontburners.com",
	"www.cooks.com",
	"www.cooks.com_recipe",
	"www.couponsandfreebiesmom.com",
	"www.cozycountryliving.com",
	"www.craftsalamode.com",
	"www.deliciousobsessions.com",
	"www.epicurious.com",
	"www.girlversusdough.com",
	"www.herbwisdom.com",
	"www.italianfoodforever.com",
	"www.joepastry.com",
	"www.jugglingactmama.com",
	"www.kingarthurflour.com",
	"www.lemonsandlaughs.com",
	"www.littlemisscelebration.com",
	"www.makeminelemon.com",
	"www.martaskitchen.my",
	"www.marthas-kitchen.org",
	"www.plaisiretgourmandisechezsophie.com",
	"www.quickneasyrecipes.net",
	"www.recipesforourdailybread.com",
	"www.roundmenu.com",
	"www.seductioninthekitchen.com",
	"www.simplegourmetcook.com",
	"www.sixsistersstuff.com",
	"www.stacymakescents.com",
	"www.tasteofhome.com",
	"www.thebakingchocolatess.com",
	"www.theharriedcook.com",
	"www.theshadyporch.com",
	"www.theslowroasteditalian.com",
	"www.theyumlist.net",
	"www.undejeunerdesoleil.com",
	"www.upstateramblings.com",
	"www.wholeyum.com",
	"www.wiveswithknives.net",
	"www.yummly.com",
	"yesterfood.blogspot.com"
};


const char *sni_cloak(void) {
	int size = sizeof(sni_list) / sizeof(char *);
	int index = rand() % size;
	return sni_list[index];
}



