#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "pkill fdns\r"
sleep 1

send -- "fdns --server=appliedprivacy\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"using cloudflare" {puts "TESTING ERROR 0.1\n";exit}
	"fdns starting"
}
expect {
	timeout {puts "TESTING ERROR 0.2\n";exit}
	"using cloudflare" {puts "TESTING ERROR 0.3\n";exit}
	"SSL connection opened"
}
sleep 1

spawn $env(SHELL)
send "rm /tmp/index.html\r"
after 100
send -- "firejail --dns=127.1.1.1 wget -O /tmp/index.html google.com\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Connecting to www.google.com"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"index.html"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"saved"
}
after 100
send "rm /tmp/index.html\r"
send -- "pkill fdns\r"

after 100
puts "\nall done\n"
