#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019-2021 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "pkill fdns\r"
sleep 1

send -- "fdns\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"fdns starting"
}
expect {
	timeout {puts "TESTING ERROR 0.1\n";exit}
	"SSL connection opened"
}
sleep 1

spawn $env(SHELL)
send -- "firejail --dns=127.1.1.1 ping -c 3 google.com\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"icmp_seq=1"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"icmp_seq=2"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"icmp_seq=3"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"3 received"
}
after 100
send -- "pkill fdns\r"

after 100
puts "\nall done\n"
