#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019-2021 FDNS Authors
# License GPL v2

set timeout 20
spawn $env(SHELL)
match_max 100000

send -- "pkill fdns\r"
sleep 2

send -- "fdns --server-list=$env(SERVER_LIST) --server=https://dns.quad9.net/dns-query --fallback-server=9.9.9.9 --proxy-addr=127.9.9.9 --keepalive=7\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"fdns starting"
}
expect {
	timeout {puts "TESTING ERROR 0.1\n";exit}
	"configuring fallback server 9.9.9.9"
}
expect {
	timeout {puts "TESTING ERROR 0.2\n";exit}
	"SSL connection opened"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"keepalive 7"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"keepalive 7"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"keepalive 7"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"keepalive 7"
}
sleep 2

spawn $env(SHELL)
send -- "fdns --server-list=$env(SERVER_LIST) --test-server=dot://9.9.9.9 --details\r"
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"URL: dot://9.9.9.9"
}
expect {
	timeout {puts "TESTING ERROR 11\n";exit}
	"Port: 853"
}
expect {
	timeout {puts "TESTING ERROR 12\n";exit}
	"Network trace:"
}
expect {
	timeout {puts "TESTING ERROR 13\n";exit}
	"DoT query average"
}
expect {
	timeout {puts "TESTING ERROR 14\n";exit}
	"Testing completed"
}

after 100
send -- "pkill fdns\r"

after 100
puts "\nall done\n"
