#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019-2020 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "fdns --list=adblocker\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Current zone:"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"adguard"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"servers found"
}


after 100
puts "\nall done\n"

