#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019-2025 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "fdns --server-list=$env(SERVER_LIST) --list=all\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Current zone:"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"cleanbrowsing"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"cleanbrowsing-family"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"cloudflare"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"quad9"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"twnic"
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"servers found"
}


after 100
puts "\nall done\n"

