#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019-2021 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "fdns --list=OpenNIC --zone=Asia-Pacific\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Current zone: AsiaPacific"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"seby"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"seby2"
}


after 100
puts "\nall done\n"

