#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "fdns --list\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"appliedprivacy"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"cleanbrowsing"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"cleanbrowsing-family"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"cloudflare"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"powerdns"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"quad9"
}


after 100
puts "\nall done\n"

