#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019-2021 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "fdns --list=Americas\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Current zone:"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"adguard"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"dnscrypt-ca"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"nextdns"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"pi-dns"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"servers found"
}

send -- "fdns --list\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"Current zone:"
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"quad9"
}
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"quad9-2"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"servers found"
}


after 100
puts "\nall done\n"

