#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019-2020 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

spawn $env(SHELL)
send -- "firejail --dns=127.1.1.1 ping -c 3 doubleclick.net\r"
set ping_id $spawn_id

spawn $env(SHELL)
set monitor_id $spawn_id
send -- "fdns --monitor\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"doubleclick.net, dropped"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"doubleclick.net (ipv6), dropped"
}
after 100
puts "\nall done\n"

