#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019-2025 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "pkill fdns\r"
sleep 2

send -- "fdns --list\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Error" {puts "TESTING ERROR 1\n";exit}
	"adguard"
}
sleep 1

send -- "fdns --list=dot\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Error" {puts "TESTING ERROR 3\n";exit}
	"adguard-dot"
}
sleep 1

send -- "fdns --list=quic\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Error" {puts "TESTING ERROR 3\n";exit}
	"adguard-quic"
}
sleep 1


send -- "fdns --nofilter --server=adguard --details\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Error" {puts "TESTING ERROR 5\n";exit}
	"Testing server"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"Error" {puts "TESTING ERROR 7\n\n";exit}
	"HTTP Header"
}
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"Error" {puts "TESTING ERROR 9\n";exit}
	"DoH/DNS bandwidth ratio"
}
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"Error" {puts "TESTING ERROR 11\n";exit}
	"fdns starting"
}
expect {
	timeout {puts "TESTING ERROR 12\n";exit}
	"Error" {puts "TESTING ERROR 13\n";exit}
	"SSL connection opened"
}
sleep 1
spawn $env(SHELL)
sleep 1
send -- "pkill fdns\r"
sleep 1





send -- "fdns --nofilter --server=adguard-dot --details\r"
expect {
	timeout {puts "TESTING ERROR 14\n";exit}
	"Error" {puts "TESTING ERROR 15\n";exit}
	"Testing server"
}
expect {
	timeout {puts "TESTING ERROR 16\n";exit}
	"Error" {puts "TESTING ERROR 17n";exit}
	"URL: dot://"
}
expect {
	timeout {puts "TESTING ERROR 18\n";exit}
	"Error" {puts "TESTING ERROR 19\n";exit}
	"Network trace"
}
expect {
	timeout {puts "TESTING ERROR 20\n";exit}
	"Error" {puts "TESTING ERROR 21\n";exit}
	"DoT/DNS bandwidth ratio"
}
expect {
	timeout {puts "TESTING ERROR 22\n";exit}
	"Error" {puts "TESTING ERROR 23\n";exit}
	"fdns starting"
}
expect {
	timeout {puts "TESTING ERROR 24\n";exit}
	"Error" {puts "TESTING ERROR 25\n";exit}
	"SSL connection opened"
}
sleep 1
spawn $env(SHELL)
sleep 1
send -- "pkill fdns\r"
sleep 1


send -- "fdns --nofilter --server=adguard-quic --details\r"
expect {
	timeout {puts "TESTING ERROR 14\n";exit}
	"Error" {puts "TESTING ERROR 15\n";exit}
	"Testing server"
}
expect {
	timeout {puts "TESTING ERROR 16\n";exit}
	"Error" {puts "TESTING ERROR 17n";exit}
	"URL: quic://"
}
expect {
	timeout {puts "TESTING ERROR 18\n";exit}
	"Error" {puts "TESTING ERROR 19\n";exit}
	"Network trace"
}
#expect {
#	timeout {puts "TESTING ERROR 20\n";exit}
#	"Error" {puts "TESTING ERROR 21\n";exit}
#	"DoT/DNS bandwidth ratio"
#}
expect {
	timeout {puts "TESTING ERROR 22\n";exit}
	"Error" {puts "TESTING ERROR 23\n";exit}
	"fdns starting"
}
expect {
	timeout {puts "TESTING ERROR 24\n";exit}
	"Error" {puts "TESTING ERROR 25\n";exit}
	"SSL connection opened"
}
sleep 1
spawn $env(SHELL)
sleep 1
send -- "pkill fdns\r"
sleep 1




after 100
puts "\nall done\n"
