#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

########################
puts "TESTING:    packet length test"
send -- "../src/ptest/ptest test1 > ptest1.out\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Testing done"
}
after 100
send -- "diff -s ptest1.out ptest1.master\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"are identical"
}
after 100
send -- "rm ptest1.out\r"
after 100

########################
puts "TESTING:    packet class test"
send -- "../src/ptest/ptest test2 > ptest2.out\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Testing done"
}
after 100
send -- "diff -s ptest2.out ptest2.master\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"are identical"
}
after 100
send -- "rm ptest2.out\r"
after 100


########################
puts "TESTING:    packet rr type test"
send -- "../src/ptest/ptest test3 > ptest3.out\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Testing done"
}
after 100
send -- "diff -s ptest3.out ptest3.master\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"are identical"
}
after 100
send -- "rm ptest3.out\r"
after 100

########################
puts "TESTING:    wrong question/answer section"
send -- "../src/ptest/ptest test4 > ptest4.out\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Testing done"
}
after 100
send -- "diff -s ptest4.out ptest4.master\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"are identical"
}
after 100
send -- "rm ptest4.out\r"
after 100

########################
puts "TESTING:    compressed question"
send -- "../src/ptest/ptest test5 > ptest5.out\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"Testing done"
}
after 100
send -- "diff -s ptest5.out ptest5.master\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"are identical"
}
after 100
send -- "rm ptest5.out\r"
after 100


########################
puts "TESTING:    classic exploits"
send -- "../src/ptest/ptest test6 > ptest6.out\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"Testing done"
}
after 100
send -- "diff -s ptest6.out ptest6.master\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"are identical"
}
after 100
send -- "rm ptest6.out\r"
after 100


########################
puts "TESTING:    DSN flags"
send -- "../src/ptest/ptest test7 > ptest7.out\r"
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"Testing done"
}
after 100
send -- "diff -s ptest7.out ptest7.master\r"
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"are identical"
}
after 100
send -- "rm ptest7.out\r"
after 100




after 100
puts "\nall done\n"


