#!/usr/bin/expect -f
# This file is part of fdns project
# Copyright (C) 2019-2021 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "pkill fdns\r"
sleep 2

send -- "fdns --server-list=$env(SERVER_LIST) --server=anycast --transport=dot\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"connecting to adguard-unfiltered-dot server"  {puts "1"}
	"connecting to adguard-unfiltered2-dot server"  {puts "1"}
	"connecting to adguard-dot server"  {puts "1"}
	"connecting to adguard2-dot server"  {puts "1"}
	"connecting to nextdns-dot server" {puts "4"}
	"connecting to nextdns2-dot server" {puts "4"}
}

after 100
puts "\nall done\n"
