#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "pkill fdns\r"
sleep 1

send -- "fdns --server=non-profit --debug 2>&1\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"tag 42l"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"tag appliedprivacy"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"tag digital-society"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"tag index 1" {puts "1"}
	"tag index 2" {puts "2"}
	"tag index 3" {puts "3"}
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"connecting to 42l server"  {puts "1"}
	"connecting to appliedprivacy server"  {puts "2"}
	"connecting to digital-society server" {puts "3"}
}

after 100
puts "\nall done\n"
