#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019-2021 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "fdns --test-server=anycast\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"adguard"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"SSL/TLS connection"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"DoH query average"
}

after 100
puts "\nall done\n"

