#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019-2021 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "fdns --test-url=doubleclick.net\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"URL doubleclick.net dropped by default rule \"click.\""
}
after 100

send -- "fdns --test-url=amazon-adsystem.com\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"URL amazon-adsystem.com dropped by default rule"
}
after 100

send -- "fdns --test-url=debian.org\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"URL debian.org is not dropped"
}


after 100
puts "\nall done\n"

