#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019-2025 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "fdns --server-list=$env(SERVER_LIST) --test-server\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Testing server"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"SSL/TLS connection"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"DoH query average"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Testing server"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"SSL/TLS connection"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"DoH query average"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"Testing server"
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"SSL/TLS connection"
}
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"DoH query average"
}




after 100
puts "\nall done\n"

