#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019-2025 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "fdns --server-list=$env(SERVER_LIST) --test-url-list\r"
after 200

send -- "gentoo.org\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"127.0.0.1 gentoo.org"
}
after 100

send -- "127.0.0.1 gentoo.org\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"127.0.0.1 gentoo.org"
}

after 100
puts "\nall done\n"

