#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019-2021 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "fdns --list transport=bla\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"invalid command line argument"
}
after 100
send -- "fdns --list --transport=bla\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"invalid DNS transport"
}
after 100

send -- "fdns --list=all --transport=dot\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"digital-society"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"sinodun-dot"
}

send -- "fdns --list --transport=dot --zone=Europe\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"containerpi-dot" {puts "TESTING ERROR 6\n";exit}
	"sinodun-dot"
}
after 100

#send -- "fdns --test-server --transport=dot --zone=AsiaPacific\r"
#expect {
#	timeout {puts "TESTING ERROR 8\n";exit}
#	"appliedprivacy" {puts "TESTING ERROR 9\n";exit}
#	"appliedprivacy-dot" {puts "TESTING ERROR 10\n";exit}
#	"no such server available"
#}

after 100

puts "\nall done\n"
