#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019-2020 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "pkill fdns\r"
sleep 1

send -- "fdns --list transport=bla\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"invalid command line argument"
}
after 100
send -- "fdns --list --transport=bla\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"invalid transport"
}
after 100

send -- "fdns --list=all --transport=dot\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"cloudflare-dot"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"digital-society2"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"seby2-dot"
}

send -- "fdns --list --transport=dot --zone=Europe\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"wil.cloud2" {puts "TESTING ERROR 6\n";exit}
	"seby2-dot" {puts "TESTING ERROR 7\n";exit}
	"li-dot"
}
after 100

send -- "fdns --test-server --transport=dot --zone=EastAmerica\r"
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"appliedprivacy" {puts "TESTING ERROR 9\n";exit}
	"appliedprivacy-dot" {puts "TESTING ERROR 10\n";exit}
	"DoT/Do53 bandwidth ratio"
}
expect {
	timeout {puts "TESTING ERROR 11\n";exit}
	"appliedprivacy" {puts "TESTING ERROR 12\n";exit}
	"appliedprivacy-dot" {puts "TESTING ERROR 13\n";exit}
	"Testing server cloudflare2-dot"
}

after 100

send -- "fdns --test-server=family --transport=dot --zone=EastAmerica\r"
expect {
	timeout {puts "TESTING ERROR 12\n";exit}
	"appliedprivacy" {puts "TESTING ERROR 13\n";exit}
	"appliedprivacy-dot" {puts "TESTING ERROR 14\n";exit}
	"Testing server cloudflare-family-dot"
}
expect {
	timeout {puts "TESTING ERROR 15\n";exit}
	"appliedprivacy" {puts "TESTING ERROR 16\n";exit}
	"appliedprivacy-dot" {puts "TESTING ERROR 17\n";exit}
	"DoT/Do53 bandwidth ratio"
}
expect {
	timeout {puts "TESTING ERROR 18\n";exit}
	"appliedprivacy" {puts "TESTING ERROR 19\n";exit}
	"appliedprivacy-dot" {puts "TESTING ERROR 20\n";exit}
	"Testing server cloudflare-family2-dot"
}
after 100


send -- "fdns --server=anycast --transport=dot\r"
expect {
	timeout {puts "TESTING ERROR 21\n";exit}
	"Testing server"
}
expect {
	timeout {puts "TESTING ERROR 22\n";exit}
	"DoT/Do53 bandwidth ratio"
}
expect {
	timeout {puts "TESTING ERROR 23\n";exit}
	"Testing server"
}
expect {
	timeout {puts "TESTING ERROR 24\n";exit}
	"DoT/Do53 bandwidth ratio"
}
expect {
	timeout {puts "TESTING ERROR 25\n";exit}
	"dot transport up"
}

after 100
puts "\nall done\n"
