#!/usr/bin/expect -f
# This file is part of FDNS project
# Copyright (C) 2019-2021 FDNS Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "pkill fdns\r"
sleep 2

send -- "fdns --transport=udp\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"fdns starting"
}
sleep 3

spawn $env(SHELL)
send -- "firejail --dns=127.1.1.1 nslookup google.com\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Address"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"127.1.1.1#53"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Non-authoritative answer:"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"google.com"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"Address"
}
after 100

send -- "firejail --dns=127.1.1.1 nslookup gentoo.org\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"Address"
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"127.1.1.1#53"
}
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"Non-authoritative answer:"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"gentoo.org"
}
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"Address"
}
after 100

send -- "firejail --dns=127.1.1.1 nslookup debian.org\r"
expect {
	timeout {puts "TESTING ERROR 11\n";exit}
	"Address"
}
expect {
	timeout {puts "TESTING ERROR 12\n";exit}
	"127.1.1.1#53"
}
expect {
	timeout {puts "TESTING ERROR 13\n";exit}
	"Non-authoritative answer:"
}
expect {
	timeout {puts "TESTING ERROR 14\n";exit}
	"debian.org"
}
expect {
	timeout {puts "TESTING ERROR 15\n";exit}
	"Address"
}

sleep 1

spawn $env(SHELL)
send -- "fdns --monitor\r"
expect {
	timeout {puts "TESTING ERROR 20\n";exit}
	"NOT ENCRYPTED"
}
expect {
	timeout {puts "TESTING ERROR 21\n";exit}
	"not encrypted"
}

after 100
puts "\nall done\n"
